version: '3.9'
services:
  blog:
    image: jekyll/jekyll:4.2.0
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle # allow cache to be re-usable
    ports:
      - 4000:4000
    command: jekyll serve
